spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&requireSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        # On Hibernate 6+, MySQL dialect auto-detects; no need to set explicitly.

  flyway:
    enabled: true
    # No 'schemas' for MySQL; just point to your MySQL migrations folder.
    locations: classpath:db/migration-mysql
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: ${PORT:10000}

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.flywaydb: INFO