server:
  port: ${PORT:10000}   # Render/containers set PORT; fallback for local

spring:
  application:
    name: compare-my-device
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none         # Flyway owns the schema
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true   # first time: creates flyway_schema_history at V1

management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.flywaydb: INFO