spring:
  datasource:
    url: jdbc:h2:mem:cmd;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

  flyway:
    locations: classpath:db/migration-h2
    enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080