spring:
  datasource:
    # If app runs on the same Hostinger server, you can use 127.0.0.1 instead of the MySQL host name.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:${DB_HOST}}:${MYSQL_PORT:3306}/${MYSQL_DB}?useSSL=true&requireSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
    username: ${MYSQL_USER:${DB_USERNAME}}
    password: ${MYSQL_PASS:${DB_PASSWORD}}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        # On Hibernate 6+, MySQL dialect auto-detects; no need to set explicitly.

  flyway:
    enabled: true
    # No 'schemas' for MySQL; just point to your MySQL migrations folder.
    locations: classpath:db/migration-mysql
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: ${PORT:10000}

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.flywaydb: INFO