spring:
  datasource:
    # If app runs on the same Hostinger server, you can use 127.0.0.1 instead of the MySQL host name.
    url: jdbc:mysql://${DB_HOST:mysql-xxxx.hostinger.com}:3306/u229745468_comparemydevic?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=UTC&useSSL=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:u229745468_comparemydevic}
    password: ${DB_PASSWORD:H@YGX3*w}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        # On Hibernate 6+, MySQL dialect auto-detects; no need to set explicitly.

  flyway:
    enabled: true
    # No 'schemas' for MySQL; just point to your MySQL migrations folder.
    locations: classpath:db/migration-mysql
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: ${PORT:10000}

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: WARN
    org.flywaydb: INFO