spring:
  config:
    activate:
      on-profile: h2

  datasource:
    url: jdbc:h2:mem:cmd;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true

  flyway:
    # Use the H2-specific scripts you prepared
    locations: classpath:db/migration-h2

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE