# application-prod.yml

server:
  port: ${PORT:10000}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:${PGHOST}}:${DB_PORT:${PGPORT:5432}}/${DB_NAME:${PGDATABASE}}
    username: ${DB_USERNAME:${PGUSER}}
    password: ${DB_PASSWORD:${PGPASSWORD}}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        # Let Hibernate auto-pick the dialect for Postgres 16
        # dialect: org.hibernate.dialect.PostgreSQLDialect  # <-- remove this warning source

  flyway:
    enabled: true
    locations: classpath:db/migration-postgres
    baseline-on-migrate: true
    validate-on-migrate: true
    schemas: public
    create-schemas: false
    placeholder-replacement: true
    placeholders:
      RESET_SCHEMA: "false"   # flip to "true" for a single deploy only

logging:
  level:
    org.flywaydb: INFO
    org.springframework: INFO
    org.hibernate.SQL: WARN