# DO NOT put 'spring.profiles' here.
# If you really want to guard it, you can use:
# spring:
#   config:
#     activate:
#       on-profile: prod

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:${RENDER_EXTERNAL_HOSTNAME}}:${DB_PORT:5432}/${DB_NAME}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        # Dialect is auto-detected; leaving it out avoids the deprecation warning.
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration-postgres
    baseline-on-migrate: true
    validate-on-migrate: false
    placeholder-replacement: true
    clean-disabled: true
    # If you still need the one-time conditional reset V2 script:
    # placeholders:
    #   RESET_SCHEMA: "false"

logging:
  level:
    org.flywaydb: INFO
    org.springframework: INFO