server:
  # Bind to Render's PORT (defaults to 10000 if not set)
  port: ${PORT:10000}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        # Do NOT set hibernate.dialect explicitly; Hibernate picks Postgres automatically.

  flyway:
    enabled: true
    locations: classpath:db/migration-postgres
    schemas: public
    baseline-on-migrate: true
    ignore-missing-migrations: true    # ONE deploy only
    validate-on-migrate: false         # ONE deploy only
    clean-disabled: true
    placeholder-replacement: true
    placeholders:
      RESET_SCHEMA: "true"   # keep off unless you *really* want to drop everything
    repair-on-migrate: true   # <-- ONE DEPLOY ONLY

logging:
  level:
    org.flywaydb: INFO
    org.springframework: INFO
    org.hibernate.SQL: WARN