spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        # default_schema: public  # optional

  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration-postgres
    baseline-on-migrate: true
    validate-on-migrate: true
    placeholder-replacement: true
    placeholders:
      RESET_SCHEMA: "false"     # set "true" for ONE deploy if you want V2 to drop+recreate, then back to false
    clean-disabled: true        # safer: disallow flyway clean in prod

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.flywaydb: INFO
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

# IMPORTANT for Render: bind to their assigned port
server:
  port: ${PORT:8080}