spring:
  datasource:
    url: jdbc:postgresql://dpg-d21r7s2dbo4c73eho1k0-a:5432/comparemydevice_db
    username: comparemydevice_db_user
    password: jpCrKdT2gxd71ZgUo042SHYIBcv1JsUd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

logging:
  level:
    org.springframework: INFO